FROM webhippie/python:latest-arm64v8

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Docker Custodian" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/dcgc"]

RUN apk update && \
  apk upgrade && \
  pip3 install -U pip docker-custodian && \
  rm -rf /var/cache/apk/*
